-- crawler_service 数据库
CREATE DATABASE "${CRAWLER_DB_NAME}";
CREATE USER "${CRAWLER_DB_USER}" WITH PASSWORD "${CRAWLER_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${CRAWLER_DB_NAME}" TO "${CRAWLER_DB_USER}";
\c "${CRAWLER_DB_NAME}"
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${CRAWLER_DB_USER}";

-- data_source_service 数据库
CREATE DATABASE "${DATA_SOURCE_DB_NAME}";
CREATE USER "${DATA_SOURCE_DB_USER}" WITH PASSWORD "${DATA_SOURCE_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${DATA_SOURCE_DB_NAME}" TO "${DATA_SOURCE_DB_USER}";
\c "${DATA_SOURCE_DB_NAME}"
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${DATA_SOURCE_DB_USER}";

-- ai_service 数据库
CREATE DATABASE "${AI_DB_NAME}";
CREATE USER "${AI_DB_USER}" WITH PASSWORD "${AI_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${AI_DB_NAME}" TO "${AI_DB_USER}";
\c "${AI_DB_NAME}"
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${AI_DB_USER}";

-- occupation_service 数据库
CREATE DATABASE "${OCCUPATION_DB_NAME}";
CREATE USER "${OCCUPATION_DB_USER}" WITH PASSWORD "${OCCUPATION_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${OCCUPATION_DB_NAME}" TO "${OCCUPATION_DB_USER}";
\c "${OCCUPATION_DB_NAME}"
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${OCCUPATION_DB_USER}";

-- user_service 数据库
CREATE DATABASE "${USER_DB_NAME}";
CREATE USER "${USER_DB_USER}" WITH PASSWORD "${USER_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${USER_DB_NAME}" TO "${USER_DB_USER}";
\c "${USER_DB_NAME}"
GRANT ALL ON SCHEMA public TO "${USER_DB_USER}";

-- university_service 数据库
CREATE DATABASE "${UNIVERSITY_DB_NAME}";
CREATE USER "${UNIVERSITY_DB_USER}" WITH PASSWORD "${UNIVERSITY_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${UNIVERSITY_DB_NAME}" TO "${UNIVERSITY_DB_USER}";
\c "${UNIVERSITY_DB_NAME}"
GRANT ALL ON SCHEMA public TO "${UNIVERSITY_DB_USER}";

-- file_service 数据库
CREATE DATABASE "${FILE_DB_NAME}";
CREATE USER "${FILE_DB_USER}" WITH PASSWORD "${FILE_DB_PASSWORD}";
GRANT ALL PRIVILEGES ON DATABASE "${FILE_DB_NAME}" TO "${FILE_DB_USER}";
\c "${FILE_DB_NAME}"
GRANT ALL ON SCHEMA public TO "${FILE_DB_USER}";
