#!/bin/bash
# 百工谱 — PostgreSQL 初始化脚本
set -e

# crawler_service
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${CRAWLER_DB_NAME}";
CREATE USER "${CRAWLER_DB_USER}" WITH PASSWORD '${CRAWLER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE "${CRAWLER_DB_NAME}" TO "${CRAWLER_DB_USER}";
\c "${CRAWLER_DB_NAME}"
ALTER DATABASE "${CRAWLER_DB_NAME}" SET timezone TO 'Asia/Shanghai';
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${CRAWLER_DB_USER}";

\i ./service-init/crawler_init.sql

-- 表由 postgres 用户创建，需将表与序列权限授予服务用户
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${CRAWLER_DB_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${CRAWLER_DB_USER}";
SQL

# data_source_service
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${DATA_SOURCE_DB_NAME}";
CREATE USER "${DATA_SOURCE_DB_USER}" WITH PASSWORD '${DATA_SOURCE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE "${DATA_SOURCE_DB_NAME}" TO "${DATA_SOURCE_DB_USER}";
\c "${DATA_SOURCE_DB_NAME}"
ALTER DATABASE "${DATA_SOURCE_DB_NAME}" SET timezone TO 'Asia/Shanghai';
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${DATA_SOURCE_DB_USER}";

\i ./service-init/data_source_init.sql

-- 表由 postgres 用户创建，需将表与序列权限授予服务用户
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${DATA_SOURCE_DB_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${DATA_SOURCE_DB_USER}";
SQL

# occupation_service
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${OCCUPATION_DB_NAME}";
CREATE USER "${OCCUPATION_DB_USER}" WITH PASSWORD '${OCCUPATION_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE "${OCCUPATION_DB_NAME}" TO "${OCCUPATION_DB_USER}";
\c "${OCCUPATION_DB_NAME}"
ALTER DATABASE "${OCCUPATION_DB_NAME}" SET timezone TO 'Asia/Shanghai';
CREATE EXTENSION IF NOT EXISTS vector;
GRANT ALL ON SCHEMA public TO "${OCCUPATION_DB_USER}";

\i ./service-init/occupation_init.sql
\i ./service-init/occupation_data.sql

-- 表由 postgres 用户创建，需将表与序列权限授予服务用户
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${OCCUPATION_DB_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${OCCUPATION_DB_USER}";
SQL

# user_service
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${USER_DB_NAME}";
CREATE USER "${USER_DB_USER}" WITH PASSWORD '${USER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE "${USER_DB_NAME}" TO "${USER_DB_USER}";
\c "${USER_DB_NAME}"
ALTER DATABASE "${USER_DB_NAME}" SET timezone TO 'Asia/Shanghai';
GRANT ALL ON SCHEMA public TO "${USER_DB_USER}";

\i ./service-init/user_init.sql
\i ./service-init/user_data.sql

-- 表由 postgres 用户创建，需将表与序列权限授予服务用户
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${USER_DB_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${USER_DB_USER}";
SQL

# file_service
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE "${FILE_DB_NAME}";
CREATE USER "${FILE_DB_USER}" WITH PASSWORD '${FILE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE "${FILE_DB_NAME}" TO "${FILE_DB_USER}";
\c "${FILE_DB_NAME}"
ALTER DATABASE "${FILE_DB_NAME}" SET timezone TO 'Asia/Shanghai';
GRANT ALL ON SCHEMA public TO "${FILE_DB_USER}";
SQL

echo "百工谱数据库初始化完成"
