-- 百工谱 AI 服务独立数据库初始化：仅保存业务审计上下文，不保存模型输入或输出正文。

CREATE TYPE "level" AS ENUM ('INFO', 'ERROR', 'WARNING');
CREATE TYPE "request_method" AS ENUM ('GET', 'POST', 'PUT', 'DELETE');

CREATE TABLE "logs" (
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    "deleted_at" timestamp with time zone,
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "trace_id" bigint,
    "user_id" bigint NOT NULL,
    "user_name" varchar(64) NOT NULL,
    "user_ip" varchar(64),
    "level" level NOT NULL,
    "request_method" request_method,
    "request_url" varchar(256),
    "error_msg" text,
    "detail" text
);

CREATE INDEX "idx_logs_trace_id" ON "logs" ("trace_id")
    WHERE "deleted_at" IS NULL;
